# Internal filename: install.py
# Bytecode version: 3.12.0rc2 (3531)
import sys
import os
import base64
import zipfile
import tkinter as tk
from tkinter import ttk, filedialog, messagebox
import threading
import pygame
import ctypes
import ttkbootstrap as tb
from PIL import Image, ImageTk, ImageSequence
import winreg
import subprocess

def run_as_admin():
    if sys.platform == 'win32':
        if ctypes.windll.shell32.IsUserAnAdmin():
            return
        ctypes.windll.shell32.ShellExecuteW(None, 'runas', sys.executable, ' '.join(sys.argv), None, 1)
        sys.exit()
    else:  # inserted
        if sys.platform == 'darwin':
            if os.geteuid()!= 0:
                script = f'do shell script \"{sys.executable} {sys.argv[0]}\" with administrator privileges'
                os.system(f'osascript -e \'{script}\'')
                sys.exit()
run_as_admin()
encoded_data = b'UEsDBBQAAAAAAAKWdFoAAAAAAAAAAAAAAAAXAAAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC9QSwMEFAAAAAgAxq1UWV1iA1yLKAAAEKwAACUAAABjb20uZXh0ZW5zaW9uLmF1dG9zbG90L0NTSW50ZXJmYWNlLmpz7R3pcvM08DfM8A4m/CAFN+Ur9xEgtAECvaZpuZmOmziJwbGD7bQNx7uzh27ZOfjKMUA4mljSarW7Wq1Wu/LBS3/657ln8d+gd3z+UT8Yfj286p8Og8HZ0fnlxfll76p/jKVH+WJVJNNZFRy+cvhK0Bvnt3EwXJVVPC+DQTbKi0VeRFU8JlBpGlxi5TK4jMu4uIvHHdHL2fnV4Kj/TiAgLOJinkC1Vb4MqjxYlnEYzPNxMlmFQZSNg3FSVkVyu6zioJolZTBJ0jhIsiAaQY/jKBvFwX1SzaAwRugVgCuDfIK/RQ9pMoqzMg6iaRHH8zirqO18EWWrJJsGSdUJgsGEEJhFd3FQxKM4AYSN/iZFPg8ihF/mywK6zAF8ARWijDsJsb8MYRTGEJJRVCV5FgZ5ocaBDwA/6BY6+mmZFHFJuC6KJC+wh/siqSqARYQpS67OvQgS/umfg+eefe7Zg5eA58NBBhSdRDDk/eDuySsd+CeQ5YBL8FIwrHIcwyjPyirKKqBYjpRBtmTj/D6oVgsoLpcLEI8KqHq7wlIA/dUQ+DgpIqDLclQtCxwewZ4ssxGSiep8SVCuAEh777lnf3nu2d8UcqJH2SFVN3sNLqIsTjsE0wbVubnonfVPgm7Qojqtd7cHepqP4zQuy3q4p+fH/ZP+cIigZc0doUfpcRKl+bSxg97JzfGgd3L+CXWiG+h++ndROhwVyaIK4qKAvuaARjSNCaIuvOkXxSmXICi3VQcBakZ/OEqjsgy+iAsUSnp0HE+SDLgbBXf8NMiW89u44Ck5j37IC5gKScZ/RkXOc7pcxCPAmEDgTMwzmJVA0KtZbDXCytwuANSW2FERYxdxkYzeRQKaoLhOMII5CbMeZneAMy6boliJESyiIppzF0Ggu5PYa2RCGNIiL5MquUNtU8VTGNRygRoqgxHDbJ6i0kpzBK9BI9oSNH5/XNBABwbN3x8PtCAigpbfa4FnQP/bpCqiooa2RQxzGNRhkMX3wXcjKSdBfvtDPKrcuS2L23VCIpHgCQ9jJlXcYV51mWfvGgXQmArgr11A4KCA/poFcpRd2RUU/mYIu5CNh2S+nAu5itI0v4/HNHUjKYQ+mTrcHDoB/T5JYeig35uA4UJ2kS6n+B8Ku6iZJZO4rIJyNIvnkaScIFjntPfVzdn1KaD+tvysmaYf5cts7MzVW3wGPOShqCEUUTaFlet+loxmAYDIgS4VNvC5iQBpjkPhJI2mCAkaxrgq4sqWQKsMBjdKlyXKIpTGD+KH6t6dlxIRlnHs9AVPhnRlDfyqAIImE2KsHht8l1VgUJMoLbESI6eR2Sy/RMBmIdZ12gL9UPfryK8cX1eO1JRIPZ6uBoBS2czbS2SYzVtmIhgMsosSzBGYp1CCAldo+kQ4qgWOAqYBLM6qzGcMN6VBupzhhz57EOIWTcgyypZpigIksWfBynIHq82sIno0s0rXaesBhQamDruMUXcNEphMg7a6iv7RwLbLZVYlc+bYZbwAqwmXPRw2F4DCSNGABn3NxkH/os5CCvoPYB8Sc2mxG8cAvojh7yLOxnE2SkASYMTAiCoZLaEMWyE02ZESDgBPPcUSolI+ngxkEbTjqSnB0LNO3QzuMcN9tqDJXAGmvrhGaTJWeDXzWhCxic2yuI2ohQBPY+Bwl8bTpSGYHDVaYLH50+KqZKpmBj7rZ6NoUS5T1ptI8v3bqIzHmsDIW7lpCKLFIhV7BDbtFSGBFuojqb7Mkp9Q0wGLK9hbwNTIWekJ6AzFYpgLIs1HQOefo9s0xg3JIo1WVG89pHmUZBdRNTMhLeC33Ga1EhC7h86smqct2i+ZjXH8TmN8xhDW93uvzF5jFPbGQqBAKIrntTAD9/MFyZu2KlkmaXtCsmub3TZWYxqNxogaR8u0EmWAyiJ5iNNyW+wU7FmMe+Za2KLsKYCDdfSlwl3bqGiVPDXiAOdTws+H/QiIRw8u4vjscRCPHlzE8dnjIC5Yp1TEcVRFX83ZztYaYQxPcftcRSiAQiXLtiiMun1SwqwZzQbZJA/KeCR8Cc0q3LXw/xAmhpbaRzjo13gktIQHZCy09klSMh96uNMoohVA8XQ+exjkGlQKGDRz17AiKXvLKv8iKRPUffSxDUeNKPy4E/XgV5pHYzCgbFhoryeZIkAzrFlUwmY0znBxTvOVJipDwKGkY9Lk9HSWl5W/KtSsgqprvQ6ay6Aubydg4tBiqNR4qHRyaKhY/D6GR0LqQ6Uu6Nun/FBNRfomHmrtqj9Noq+2dl5BnSyENttCn/LOop6M0Xoev7t5nZfEgCL51SxGColi/OoWa7JBBf3DrjKm5vTXLGD6Qgl/cfaxX4pm8qtT/KlsrL7bg3qQ7eVXp1i1h+9++yZ91W1iZ82WuqaxKFnXuIb50LDmqdnIntNdW1jMiv6E7fqi1GC0Hw37d2Bw0aNeAN473IyMg8+iu0j6yrAcHMDSsMF2pKPQ/uPS0jWn2XjRa45hhcXchGrYXppRDm1UE/qNbQQC0vHV+uTk/KPeSQu3Vq3excXJ4Kh3NTg/a5nAUMkMxpuNS0v7s/E+jbOY/PwaVxOyVn6D8WboXHkj7NqtgGSNUIHOTkCWtpGOIRMr5GGHJo6OBql4TlfObIbm9Bz+2gUEEAror1mguqBi45chZwFhqBZVWn+l15eKOosir3KSBCxDJ22dT1Ycw6CWMl3y+QKJCYvXfknluqM0Z45aXns6uRDrE4JhO1ifAHSmcaU7au8Fc/D35ONOPXN0zaatmq7hePbVBkMcCBWCMNRct+pcD/uXN8e9qx7SBeuhYmm9WwMF3XNz6BI3JzRUfwNW+vCPzk9Pz89uPh6AQx+7YCAfI4zaXpBwhO+LpTLfxvloiWdOYqH3Ozn9+ub4/Oj6tH92RZ3MV8eiidHJh2N0F4xwZnSC65L9KQYQpcR8+IYGQPDGiBsotSwKxDduBtn/6qp/NhQAuV4TOLRoUAJNSr+IBlI8Wla4DfWhf3o+vLpxsEYoPRtzX1HnaV7gKmydSuHDfZxAWtRdQdQtXTm8/OQjhsDKmFqpyh0oRdyK6a0e+icFWItAvjXNPrnsHQ+A29h2KqprAGfgDFvT+Oz8rI8NM/A111EBUabaJhGiTI1EnMwUMShBPA7NwBiELTAfy0TpYhbxnpiIRMe4eo8sdYNw2nwLR4HI4cPXX++88n0HjoDJh6M847qdOOfJwJnC3i1xSlQSMgQ0KRmqu04ipryG4DeGGa7Fw2jMI8TG/G3X5kgZ6pu+7dqaqImtxbd2BU1KKAMP3Wpva2iuHyDk0hC0L4CjZRMhCO7igTVI0Ap0f/TTssm9raSkQTWr8rYnKDwYZ9GEWmStWQsgtYLH9NcsQDjwHP+YjwkwPKe/DcbYcVLw9lKYY4scTrnEkQqQks8uiBwrfSKDRHlFna486AIEAoXqyIyc0fE0wu/SIU3mMnxN4wkoc9l9iE3hsYDod+XisK4bhIVzdLnAEthKZLojbz48KHmY5UXyM+7VU92NMKuYLpY0rlQ7nIXJaH2r2iVdU79BbHSF9kMYrBwheQDePpgMX8GDVT2jlR4FDbYwVdlU6tcSCoDjQL55VEcoGNOkjCseM/+Q47SBNEzBJ+50BjXPU+ZKTjYPHM1EYnTCx6W0TNtzzaevNdZ6ytp12jyaUKHkEFoMtitGbZJcDaKrGm9ggLeYTK0Vbi0LKtdzqxuzUT5flhVtWVLwN0WFtUPRcwAbixMFRwJVHIWu7DLFd060l4uQZlnIszuU03vP7B6XKCR2aQ1ALFzYSYmFMHyrN2f10TzDravn1nqhhvPrjj5k9XWq264kNj9ab6lhhYiJ2f92+yBN566GalZQZOuqrsxip1Oo5TxpEMfrgSuIjvzpg1f01hFTeOwR7Dj3wTABR1wKG8qUTR25E2IoOnqEOIo+UE1hZFYEDxewF1sUcCTOkLeQdoIi0HiCosrGIiFwSL+1AWifUeg9/hKt3nhsYUTzBp4UQAbQ4GhREXU9lwENnsZ+gkMXQD2SKNPYbCt6lJ+eo8sK+l0nkdKBDGxQZPaZtUbMrwfrBByLtWg7Iwy5o+1k2SFO14FlVh0JpTlaozFhfzL8McnQCW6IqfAO7pdQFKAE4eoblyFwlqIsGCSJxCQHDqDJLZ4RG2LYfBumNFHdJhBFM8QLcbTKO/1PQbGl8J9gTFJuWIn0Ud3HgMTH0TxJV+6BHeEXTLjMdw516iANk5/FnPAhlVC2AQ4+/ygqPopGP04LPFgn9BmW3QrgFvCfrMcUtEAtMM7PhSRBuU19/xS334zcEIi8NYIhCkAJLTZiimB3xrYWfK2E2DyaybIN0JMJSvRdMqbDl/oDjOAcHhf3Sckhsp5Pyu3M0wvmvKpXCVaVti3EoSWKYT3PwlqSh80MVg38Ep+8vj5y5lnXmXim4jGxp4r6p1mtfp5060dgNqydFd3a4W3sb8gOkcaytf3q9lS0oXmtDHc92q/R1p+CoPazu6TIM/S1GRrbXKWCCKKPKpZ+XdnaaVoHh3RaGLNL1FEVZ6DLfbXwYukF0WCxjHurbXDHhW6bE4ztiP360qOn4uBTqug2vx4IAMEaENcD1do/S6hr6Xv+7SC+EqbueYbmv3GE6mjORPWPCw9WdrrXsx8NFd51GSrBt0vcLrS/1lqOaYe4SuM1NrkrRw0ayq3WFgIRGswONRNDgyHq0MIkVmgO2tEuAjTPxDPn2FN3B+X6h1OFO4Ya6rtZgXBTVfSv7c5F9Ciwtf7ltNbc65pjXTObj6JFdJukCZpXm6czLVQjo4k3Z8nLfdw/5lSBG3DQXzeJqMxuKFl5BcDiZWcNrMHR+dlwW2DJyJnrmGDwCWTlgJO8f9M/+2Rw1t8MCzMRpnSyBq1AmU3dWTS8voBkn6ubT69OT26Eh38rLLGBVoKljepg2PvopH/z8Ulv+Ok2UCEoLbrFMxpqocGumYIe8xvmoFevXcPhsJZVYR3NwyaShY3DdmZqnYR16+TOnBq1otStRdtsVic03bphmY2aZKLbNHSzcSPvu430eTc4OAiGCeZ0vY6ZRk0brUSoLT3N9RIVLRJrhcT/BMzXOocAszYZxM8F8bM6/KQOPz+jJj3Dl1w9gGaDNlmTH/HoaRF1VD4FHTYAa2pYRdXSUqiTdAValJRckKAJX1IVh9iv1xJbAD2JbuOUaaXBpPjQDiXIUBmMAztei4+E7+nUuspFpaAyYVlQIIti9OMGKFzJBuIxzqFJPfPcWm1rzKEcUyjRcphpU6hrU8zkoaRNV0I0C+WQu7KXpuAWsHFAxzbyGgki2Ct3gSNuYpBpF8YPjgFFl/HJ+F/A9VpStvW4t+Y8kKhr0OtpeX5wsL/2Y+d4bvz4QmQC0LlP8C/vmqpiJY7pdFaDXNdpJV7V5jgM2CPJ7lYAKMiOljmHqSC8d6jqe8v0ff6SJu/3RqO4XGf0meaG2sgBWGsfh9GluFF47wBAKtgn0TJz6toVLuNpUgIpKPcOpg/uFEU0V5ZXKh+4FJnNImxWhIgZoA5gRI32jknvhtAnXcMJaWCI1zgHRujTHnOSs8AxReQzKMO4DcAQ5leGp5RuEFg8l77tEVSbymCBI0hqQ89UoPCYQlsjGhY8mMxx7ACj7ferZUZzOCkssNEEsFdhSNM0v41Ss4IKqxUIsP5gn7uHRDnLl+k4oETwH2P4C6k872jqxg/RfJFyTwcHRAnOX3PCy8CTBFK0lKRLprCmohhS17q38ww2NFeIKnkfjhi/NoHdo6q/iGN9snUYNwisgv4oa6Rq2FFSCrrvJ4XPHTgWS71Z+mx4ftYBFVjGbXY9d25uIgx2ugEn8c0NBnG5m9G9vY61xdL4fRJz9iLvg81ZZfuvqYRQ5NoCVKhBocRjhEAR3WPyI3gSaCUpcgqrp8R5JSgyuZ926rnTP4/7NyHyZnja1af90/7N0fnJ+eXN0ae9s0/AGu5/ISJt4LC7Q2TojMqHsiOiMj1GGUFMQl+Yjh+KQ5MLgNe/jtWb2QSG/utYEXzwx5gVvEMpcwrTyxhScWFA67Reo/uKqCko7zpbpBbUS2IgtZE4D2r0fqwhjh6Tpo+aP217UXQp+UflW6yTjHstZFwsFUVPwIsHCibJIO2QL4AYFTFunplu7Ogb0YMIdEKRwkRYwdIAsPJlma44ap8NESxGLwxXqxiCBVtD6wTkSKHHpVRcsA4WFYdtvYgF7xwcvKiga313LnI54QTJV4J0NiSGX7J6FShopyUO/iWtDmEG5GLYQHNRG/UfxVLibO4cIMXh1yJJUV1jbscPJf+F6gyCgGsATCiDTkKBHQ1Pktugi0ucvXq9S3W4vIOwPkqyHsJoAz1DPUAIR/0l+A2rN0qe1dyUOcGhUJLNkMFixV/Eb6lvH2aFQPar05NPq2pxCZHqMG7AV1XESh0+oS1jkSrwIh3/3y4nEwgSpd3uPII1SdZCfdrDGh9RDRsUnJxk7Rc/6V+9GAYSY0BwGbt95hnf+dA1qcNV1FCeeSagU988RbJM261rYU8LhpVZtAD542WH1nE4eL08aUFf1FrOJU6shofPPPObg0YZQ060jxuB7yK/uu8zLvpTO6GxwVCg0zZpSrD1B617OhTOJ3oCdLug+yUZWooKmhL2RzVsu8B/s3/GnE7u9fc89rfMRDLhNh2aTLgQp2kKHs7OLEfjQI/BR8z8qv+M0LZsgyjsaRH2O8UKGqTDVgUP+MsFJHBb6spGlUjBwaQTK5mTSo/Wq8e/SkM9goIaon7CEW2lj7B2YOojSZ7Neuh8qLz5tKrh6ncOfSkzgPDTE0SB7tCqUn4Jq0q7JVaV1p6pJfy5pTrrUL7v+aTd4gzZsrUXvN8NXtko7YrvXfUVZvMiBbJILACNEJIctpt+tTidRqNt8dkKoW3w2ay4JHgXkDmt/oqZzNa4ML2FiYEqBucMmIoxRWv7rfV8P0rzMi6dPMd1xvAIG6gEBd/Wa6Kf2ZBqm2hAM9PwjVh/gNjL/byKaQoSOtwzElrFMbF74EMgcJ1W+Qt23oABxUm/CEJ3s84gYEMHGOm0G+6YOxL352w0lXUvJuUkqkxBqQ3wKeXqjeDiqevLQaOBrIFqSEje3dXKLnpBiq3Ak/40TX8tsDtP9626cXvRIk/1PVHrYwgW3+pgpv6V9EfcmUN+gWVJq5pZ6fj8FGE05fi6ciiACjep3xtvgF3zfzv7Hy+2o8lLNiecdwNSnIyjXQrqM9BFqAiStKQQHh+6Bdi+cAxnSu19Y+sFP1ZNTKmX1LbtdLGymSYfXynz66+2HajMMl+N6nq6NybQ3i+/SSlZo6o0vh6S69RWtWXiJRHL2rZvvWNXCkl3NTjeVvkYKVfQyKCNrXfEWX/tvrpDhfb+mx41k8U5m19Zbg345lLn6YnDzgz3fHgXb4bZrplQM6fm9u4MsxVsnWyHhgfXo+0VRLpPMeEq0jnJGLs3BR2ChEVhXXWCr/MVKjHtYFc+apGjQi05Ihqax2I+iRDnvKAC+qVv0xR1XC0nIPVkHu+23iOJELUwKU3wmNzOZpBKOH8Wd2fcS8tXArqe5AtPE7iKtK3LjEWjWSHYaHJrXxHI4wLM0DOPDCSXNK31VU4qqn3MLClL8ESXijXCb18ohzg/do5YxGlEXDp+V7zCTQAq5c0m4pqdEUwjducuoE8ZQxVrvqnznUKMKh5LZIhJjRki61Pg8YmkjbX0qdMKZ5X0OgW5VJnKujkijR3rhZMWt/pYMQFTwsHIV7xf0l4vj0UEWVLS8rNejOHkhUTjRAzClGTisBpeiCitt5Q9aHUg6sRvnrPxrFnmnATVM+ypObY9y9hwuY9KjaPPxsfl426MLIiIj8hLBvgH2EmOGDpmSemcMsYfdE+xnuCkpCNA7Q5tWXetnMirG1NwqoxXDcGsuoV5gYR4uk3QJ7kelosL/MHpVWd5pZdpXH3GIakZsNE79Sd1V7kYpTOG1ixOFy3ylqOd0/r05KJFPkxnw8r2mTg/xu3S+wV7cM/By6r3nNhebBXgVJbqYZMNEuEDMkVCkw9HSUTYKBIOxAYwG0xNEiCcnKqpNo6Y2WqLLJ/Xb1ZsfhNYvm4zofyZnwFMDpEgoTjzw/t1xCki6ovxEhdVgdAkljciAmIqPAAcDAh5neSV5oSPdF6dL3t834Mes6me/B1PPsfbt4GkhSIdrvoEAyRmbUTiN3GRk+rKRaKOe0tTudGWVC3KBpEpbYvSLBlWhWe42E3frWnIzWoFz0ao7fSF0GrgOUat1Y9jtuqyNYKbxdV9Xvy4L+7GRLNzEmMOfX1Ytl5V/CVAwjJgbObIGbe5kE3W2PdiT72Gmj6wtsmUTBXbRGS4WNOin67u0W8g56La7YuL62+XuAKiODsakXSmzFBbiZQzhEV1tU6w1AHOcCsj4CqXgcHBHFBOQF+L8jJEYxOeltKTFkSyO/b08zyNRjPRgsxNk30/xnCBmry3cp9lXCAqkIwqC5thrK68JHTVbSx6L6mn6EfLBG9ooSFpYcvHSysp9/N4VfJNS9ZVObhBFQsJYNkhpLot0TcAYmRbYg0Jjdt2OH6aQuogRBuRE+E0H0MVseSJHHXSsYulqsiWjuoEVY7qXPQIelkSLB6LjXJZwequzLb5olphS7OVCo8RQ3qPu4UpAYMql7egI1uBGGOL9OM+YQE/AYHWwftinP78zPxZWSef5pZ//QzFRedSNP6I2q6Znla9LTbfPnARS6AB9tM5KAQlWB1Ye4rVEBg0ggBKyOVsv/itQZ/vXxTNSQDaNOeh9Svvwp/3JLhOCuH51Qyevfyyu0vV3UIzUf/b7HsGqoN2bJoCT1RsjpSdjgsRBFuCJNdPJd660X7RwF+iL3fY3E4gqfG0cMFl08JHXFqi4xrgNyGpcTIphCUgDw73ZJ9+vxo7aCj9xBJT8ABoT3EzAJs0X9DU6DoYfAvgJeHrOxeMhD6JwOqB6H4rFPDDXIGhgPFP2qKrsNL9N55O+YdmL3ZeRJwQQ4ifK3pV20ZvZ/zICQgCgzLEcEFJsCqxQQcvB0/23t0w0G8FqO//wDj5if/rN9/T70iUv4Z+WSSwSSKFCSJMukjpJXmTMy1ctd5WLOFjpA0OreV8MdBdcBifr8I01nWaqhbKmhMzTiJ0BuQt9OcyV1dc1RaqRXUGIS9winJ/f99ZllBpCtWFTxnOEQ8W8KA8OJqBzokPCCx/x3Umi+6SaQTKkVr2sCUtJfXmHAN1V4vzIeIvN7QYcPFjBhd6CIT13XItEUs8EXGbYHvkc2UTXeMzRuB2BXuOioZ61P9YxQ/oDPzW/j6C2KeRtkJMQ1wRbDx/Qny+ovsW1cEXcAm03m0smBaPN9qZ1vla8xqmidatIyVxW6qgtq4gzyJh3hOSrx629vCApKGKPsDbq4s7QBlUJ4S68rtepY+SSt5ZaOpGhW7tiWGw/8QPRNiueXB2hZlDAsrm8//accD7rV55pbVlAMImXJ48JS5fXTwWJodPickQ3+JVIHFefRyU3nhqRn2RgMZ7LGSellNvPhYiT8uotx4LkVefFpHOk8dB5cnTCsqTuvm8nWI5//KN10TvqDDrEX3jtV0QFFoxeOO1fXib0hYk2gXoq4dNQPVXN0jIpNrLApgfgbFmTaFlEBe2lJeVNbXA9ZaXM3dhcT0oel3FkWxcPWTljcuHgq+AaFN1PeCwjvV7MI5363sQX1TkycHNwRQ8yR1wJa/lhWhnnTLqwtZ1k6nj2XroLubIqGnsvFRABiLdFvk9DGqrPNllwQmbGAYsnAcE+mCScNwwxieH8k5EdPqmmF8EoxH+jFOwvsjn8enV1cUB/m9IbQ+wKrQnawiySTqm5+Md4aBtaYtTpnHk85ZZWELpFDaTy1uzSIUVHb1zgK/Uqx4qVcT9voPRoB9qmJ4Rep7JM65SBregc6N857tMeY8pB038lh/KCDs7v+lfXp5fwtsTX8EEr9pKUOPm+uzzs/Mvz6Dek7X1Bmdf9E4GmOZ92TsdQvXDraoD07DuKz7w9w4I9bXmKbIWIAwycTT2EcuNE0Pv7VRga9KB6KG0qT02WrdH0b7JwfEGGeUerRYbLW52/TXFtuhxbPaND8btTWcvJV2XAUhUFCYBv/FaVMIRJCyQC5XUluTa430R1LZbz+m2pFu89HBCbmSO0tdXK4np/WJptePdW4nU8xMh59FKRH1Aozid7IuwDQvCdjzQ8wV2fviaO8RoAsdLlbg9sbN52oAO77xC0Qg84zj+oAwaZT2A+uJG3Aw3Uakg8JoW7+smnybHFwPZ4g/NEAyqREp9TITaff9ut99Zmk7zLKlh0Fud130GCal6v4s0m2AJ7WaD6A70ISaBcBitEMg5+ONBEMTgYf3VS7txmUynyk/wBWlHUQkuUr0+3ttxoHI1bqShGEczKfWSvs0E9cGp45bf3Iz4IXoqZYAAhT7FFSccr2SaqzsTO5TqzNTDgxj8GoDFsNV6KnuiRVWNETu+5RDLeEwTwOY1dCdTXjceRJeGTKkEx0+pW4usApP1h9BroUkQa8RWOZV6F4Mt7+doui1j88iB9UfcnW68JnxR1dniSKAOtJdgqCFqgmgx43t9rGs0bvF9jJhLtv4yBZVfHvlBuDhrm9JcqSu6muAoTfBqgBbK2TSWaelS1CLsRV+FQNLGDfS5fwuPA+AOU3k+gJNCJ00LHok8Hum3g0AOutBgTHef8g9MhjDAlB1vlP4Yy+0GiZZvzH1trkz5DGMy+ygPD6+0hds/V7UUspiGU596QqMXkxX8WBmuiJ8ecle4MwVxwIYcweDjkms5FyD0MmkDUzE2F+EqiPX7vDzxjwHyajDuttStEeMnrYBuDOm2rsC87TMgeNinND+oCp0B+Y/wpgj8SXkerQMfrA/lsCVqbaq3D/2JqttU3pfoSXwkfgrdA6PjAwlsW2QO7cE3AvdB+4DhHoxWsBWxXnXG1ERz0evm6CJQw/TG8o+VAJuKDQXAjoFtiZNnyEwMRDwsVmpaSrcKbk2yu/zHmJLcWj4+rZB68NeC68WYMyi0hvHePyo6fNG6ZSg0/PNcnUkqgpLHaLHyTdTirpqdrqQhpu14FRHeJmPfQkPtxHuGReA0FYFXpj2F0CT8AuPZ8++ocYGK0dQCjUVZ4l8jz7VIS9XfdTLOY0omlQEaFFCgRCeiSPu2E2tef0cZNKPOxGDk52NMEYENRsoBZQlLGtOS4sP4BSEG5iUcJW3T49oZsSSxIiFUE1FPie2vX2L3E3hueHBGghMSqj4Qvw7ZesdWou4E4iTSXW+J0k4jRnLzzKyhSyt0w8M0Wnu12VD4R0xkx4qxL4K6XRnr2/rpd4VJhkGE/+nr9Pn1MBkt8hQAKl/atMxQflGuIx1drCdqJTOASQ/M8nt4rG98YSNbWi/7UIdaUdCBWsYHx7B+01eKZxYRM0R+ApqIWQPAMwkomajpqRrRqoDCUuAB6WoBE7Hcw2rYKVaoRF50hCqwjFEFiE1ELDFRcT4j2EjxGWKU3kerEgdzdn1yIhDgRQRxNAyxKvoRZvgCk7HwLdBAKbCz5XKj6yliBBdnn9DtkuRxo5eBw8ZZhgsJPyS6JOKoFDfRr6DVkzeCB/jf4oHa4mggLQGSS6DhXITzEeYwFmQN58PJ2769u7Zk/LA8IdYrwUhfqFXirgGjwGmMGVNQxdBJKNILOMbb29EZ0hkRTDqS1rGGByZgpoViJr+RiAbGodQjQWcupsgvTpaNHyiYNlNxrULZYd/MUnTjxAVhbDClJK5QK3D1gDarNxn/mM3oJgXW34ikLjGxtplRvd2PIGiHqw/D+W4vfbRNM2giW9TepMZoU7zuX2jY4pMGSzcYAIu7rc5BMkcfdjkHStw8eeOrJ290FmAtHWxC47C1tWVsN0SreDdj2WsPVXe0oBUh/rhJ7WJx2NrFyt4Cgacwu23cXm3tYIcrxLYxzNcZ5er6P98g17mgf5VpzhfktBRapl3uZqZuWNbJYKhf1/EA/1+8rpPd+v/C/jcv7P+A1flpbIuGhZ1m1b9+ZcdB6lDyX/TqRtq69U7wrbV/1DX0p5WMoZ61/oc1tWiuYsVKq/z6mmJjBXVR6dfVUEK1qQ5BwbWitgpKKZQ3mhh2k9/C3UlxuDUpnJprmNCAwSZM9h1ib4OT22Yn7LbAch222PcWLevw3r41iZoWkm2abCF79W2URK9v8Ftz8ff1Rb+FjyEeh39APESbjcRVdHp6mm5Fyxoafr/7ZBZjJuPiEXTBq1vrAlFzZ1ndho6uXnTGJX5qgv22jbvbMGE/WuGS8g+1rxm5Laxs5Qf371JvcHQ/vZN7cOxfuz44/ud7uDd4fSX5fb/vljev17lm/8hV7sDgnV2zoputnbOWFKksr7tE3aOuL+qPMu9IZd3mTR8iVPq9LB4EsA65N8iVIY6trTlLxuN4U/JeyXFPXzDU3cNmTKI6wETavh+QABsW67YCnoXqfnr5zkrKNJ1bL7V50gm+hDAPsQ2Z5+MoxZmJ30BoS+um8ySjvLceImunkQaHnaBvdA+ZJskE9DO+pgNiIR9wRyVunSuiBA6r6RRnhT252xWG9ypt80RUgUZBaFsofkJxKiJExUdMv0LyHUNhw5cLyN1PYCsGX3KvBF60GtsPe3StcH8ygflr9H4YfCnOpOQLjQiJUVxgaAAILSnDdkx0x3uIeNdyG6MSHOc0vay1JqloG4q7dxEMI1k3BuYWFuMoNEEdihlQNJuZ3iUckpXws5RsMDnQPHe0qgOcxtWMdCwqEf5pls9ijNuT5eLnhpskADVSE85dRwQ7FCA2Xh5hALFarrmRCIklz+uQU+LdBeaWMy8sLdNRr35QdVQOVMW3T4n9qK0xsDAuKZeO3txApffxLXAFusNEURVE0oSU3OfPUZwmhXqd3kfLylVQ+hSUsLSPQHGGrUdHp6E14IJ3Xsgga45cpBhpSQl2NvnS9MSTJkXE+hv31ouNYOKA0TvS2B3VXHMnYW+ncDfDVgCbpcu97qrM55T/K2+eomBw+k4vfaDoVqEPSlbUGy5SvLLYeq90dp2mRq57upMF6BO8bYc0EsuKiaRk6RqMdEYl2jb3ubU8TMxMS6g3QueoTM7G3qV/Ek0EkfYPwMZwYQK9u1wkNtKdCvcRocA0RT3uUJTGKGrN2LmqfaheCEYoHYP+DGG88L0hdxFIrsOo3XjULPuIeJ/wHkgh8b1m0l9GcxF6MYeLREFHtBIyGiVcjEn3OckINXrt96ZPlPENCaJX5jqQh/zYdFUTI6D7soTQxFi7r9V9NSFddyEQwpea6IhpHE6pnGf46whk950g+BavmsdV7nvofwE9CgZDmopM6xjHEJY2psTaBG5ailJsjkkL6lqcFfRgb87EXZQwQWhRVKHn9By7AfFEMDwzRlWRQoY2opOLW3i+B833UZ4DbcRto6A+SDFIYZfv+0Ao6PJVUNt0iT3wg+S9zaElaqlgnnIAuLr8K0or6n6n/qHRY/RdzpIJ9b5L39joUXoHP23kUb5NaUrgyt3biMgptH8MPOo+mMigMrywk9s8KsZ4a6x+I5TMrcZicEHLMGuZAIGPYT2XP5UuWsJ/Yg7IG0zcMElzrumJ8y3933ejtBgaOjNee0uV/BZurv7k8NXQLhOzQfhFHhWYU8jc93uib99v9KbI1ftzR8FaxqWnfXezDDzYPsDag0cSjiqpUql1/B3sxrV91/1YqBd/p+7FLEchzhdhgFlLeMkmfjvKFyv4m6ZL3BpgUk3wMbwDbYY7JIJ1DAdj8/s4glOkrZY6GjDuCcQY+UFnk0+Mp8cV1jVZR42RXRs9WLxltiG1Qu69xtfw32MPi/qOnJka9Hxad4YJy/Jm/A5QSwMEFAAAAAAAEpV0WgAAAAAAAAAAAAAAABwAAABjb20uZXh0ZW5zaW9uLmF1dG9zbG90L0NTWFMvUEsDBBQAAAAIAGwEdVqTjY62JAIAALUFAAAoAAAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC9DU1hTL21hbmlmZXN0LnhtbJ1UXW/aMBR9plL/Q5T3xLQbUlWFVBuDDQkmVCjrq+tciCfnmsVOgf36OSYf5qNC2pvv8T3n3nP9ET3tMuG9Q664xL5/F3Z9D5DJhOO6778sRsGD/xTf3kTDnQYsk6YU+QqUvr3pLGtaz9BM3OR8LTARME76PpNZCDUcfim0nAupLyQvnRYuqv2kGfR9V8F0jupxp3jfT7XePBKy3W7D7adQ5mty3+3ekdfpZM5SyGjAUWmKDHzjxVBbOxOudGwQB/I+bjzcUAThe8ujgZG4lCRHmk0dYIU22BDfeS4xA6zK/ZBK18Wr0Ks8DkcLt8R9U8MUsbRWfyIZFVDr1LE3kEkpJETT3GHDYT7Dn4LnkDwXqHnWSJxtVE0N5q9zp6me4/uyUkQ+8h5942pDNUvHuJL/NX9LONY5uOrY/pUscgaqzLLIlHKcUZ3GIeGYwC5MdSYiUsNN3mA4Gsgso5hMOEIJH/AZzc0MNORxEADSNwEBmgH/VhFpti5nZ3wHScAkauPlajYVQm6DFTf6lBkD1/XPGMEql5kFrpMTrqwXRs0bOc82J3s2kAPsTrjCJuZPYHsmoCGXR7bkir8ZTOeFKdAirZTLq7CX8WFtg8V+A/GsPPSIlOv2TAGLuL4WEbFhS/sO0ljJ963xOf9bk+1zA75Oddx76EakWrebv3hibsXnrtmzy1aFuDI12ozLqVr7s2bs6uSydtwPw8QnGc0jOvl3LfoPUEsDBBQAAAAIAA0EdVrMsY5y3gIAAMsIAAAhAAAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC9pbmRleC5odG1stVbdbtMwFL6ftHcw0dBS1CUbu0CkaaUxdlEJxKSBEHdN49Mmw7WD7bZUVSU0brjgGXiGcTGBQLxD+kbY+Wmapi0bCEtVYp8ff+d8n924956+OH355vwMBXJAWrs7rn4i4tF+0wBqJCvgYfVEarjC52EkkeB+0zi9aFMJvOf5YF0Ko+XaqTX3laEk0DoZSnZBmEReFLl2srZIJifpJBt66zrqMjxBU71ajIHH+yF10GGjvB55GIe0XzWMQywDBx0dHt5fsQQQ9gO51sRGqhrCxg4KQoyBLplnuzvFJOxxbwBo+hdbjoKyTVXLMXAHUUZhxYRDERFv4qAuYf7bZTBZ/+y8ga6dceTq5uXtzWCGuGkMJu1kYqTMBVJGwrFt7/jh8eNHB95Rt2dJCx/0rGhsKx+fM0JCLYEJJMQmqfROJRksUeczKiTyxUIRqIkojNGSRsxaQ8cX7aKYjS1F4NkIqHwWCgkUuGkMQAivD0YdmaAtNdRsoWkeWnCQmhVsT3pKf+9rC0KKsYzIgpFHLhLgq5GNaiAHOeR0xTCrolhOxSKgrzipreC4NaqOTnCuajf3ptW0s1rnLkCrCMpcTVFKYl1leDcEIdsYzRRrxcYNtK7padTaZhelnIgJ9XNX7VgdlgyAmiYHESk8kLJcdq2Azk6eQomZPxxooH2QZwT065NJG5uF0muNdZ0vH2FLZZUq9HWqxYgJ+TxVnznNgdUX7ZnVkfFA5d2QdrapUN+TfmCawDnj/6HMfylSxW4ZeQsc1Im/zD/F3+Ov8Y/42kF706SYWae+PcGidU7xujki7++m9lY1XrIV096Q+jJktCrIQrvVI5TcV+ecDUIBiS4ZGYE+HZfgy1Xe7nrv3fIGyI+k3n5IFruuJ7fw2sJjVkfmulm8CIiALYmyPpj7ZSXEv+Kb+RWaf4hv4m/zj/HP+ef5VXytf/vlE7hC3Z/pXSwUAUtfGK6t/+qSl+zL5TdQSwECPwAUAAAAAAAClnRaAAAAAAAAAAAAAAAAFwAkAAAAAAAAABAAAAAAAAAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC8KACAAAAAAAAEAGADIa052r5nbAQAAAAAAAAAAAAAAAAAAAABQSwECPwAUAAAACADGrVRZXWIDXIsoAAAQrAAAJQAkAAAAAAAAACAAAAA1AAAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC9DU0ludGVyZmFjZS5qcwoAIAAAAAAAAQAYAJppQ1UgI9sBAAAAAAAAAAAAAAAAAAAAAFBLAQI/ABQAAAAAABKVdFoAAAAAAAAAAAAAAAAcACQAAAAAAAAAEAAAAAMpAABjb20uZXh0ZW5zaW9uLmF1dG9zbG90L0NTWFMvCgAgAAAAAAABABgAYdotbK6Z2wEAAAAAAAAAAAAAAAAAAAAAUEsBAj8AFAAAAAgAbAR1WpONjrYkAgAAtQUAACgAJAAAAAAAAAAgAAAAPSkAAGNvbS5leHRlbnNpb24uYXV0b3Nsb3QvQ1NYUy9tYW5pZmVzdC54bWwKACAAAAAAAAEAGAAi5wf835nbAQAAAAAAAAAAAAAAAAAAAABQSwECPwAUAAAACAANBHVazLGOct4CAADLCAAAIQAkAAAAAAAAACAAAACnKwAAY29tLmV4dGVuc2lvbi5hdXRvc2xvdC9pbmRleC5odG1sCgAgAAAAAAABABgAxyFnkt+Z2wEAAAAAAAAAAAAAAAAAAAAAUEsFBgAAAAAFAAUAOwIAAMQuAAAAAA=='

def get_default_install_path():
    return '/Library/Application Support/Adobe/CEP/extensions' if sys.platform == 'darwin' else 'C:\\Program Files (x86)\\Common Files\\Adobe\\CEP\\extensions'

def get_resource_path(relative_path):
    """Возвращает правильный путь к файлу внутри .exe"""  # inserted
    if getattr(sys, 'frozen', False):
        base_path = sys._MEIPASS
    else:  # inserted
        base_path = os.path.abspath('.')
    return os.path.join(base_path, relative_path)

def extract_files(destination):
    try:
        zip_path = os.path.join(destination, 'package.zip')
        with open(zip_path, 'wb') as f:
            pass  # postinserted
    except Exception as e:
            f.write(base64.b64decode(encoded_data))
                with zipfile.ZipFile(zip_path, 'r') as zip_ref:
                    zip_ref.extractall(destination)
                        os.remove(zip_path)
                        return True
            messagebox.showerror('Ошибка', f'Ошибка распаковки: {e}')
            return False

def get_csxs_versions_windows():
    csxs_versions = []
    try:
        with winreg.OpenKey(winreg.HKEY_CURRENT_USER, 'Software\\Adobe') as adobe_key:
            pass  # postinserted
    except OSError:
            i = 0
            while True:
                subkey_name = winreg.EnumKey(adobe_key, i)
                if subkey_name.startswith('CSXS.'):
                    csxs_versions.append(subkey_name)
                i += 1
        else:  # inserted
            return csxs_versions
        break

def get_csxs_versions_mac():
    try:
        output = subprocess.check_output(['defaults', 'read', 'com.adobe.CSXS'], stderr=subprocess.DEVNULL)
        return [line.split()[0] for line in output.decode().split('\n') if line.startswith('CSXS.')]
    except Exception:
        return []
    else:  # inserted
        try:
            pass  # postinserted
        pass

def set_player_debug_mode():
    try:
        if sys.platform == 'darwin':
            csxs_versions = get_csxs_versions_mac()
            for version in csxs_versions:
                os.system(f'defaults write com.adobe.{version} PlayerDebugMode 1')
        else:  # inserted
            csxs_versions = get_csxs_versions_windows()
            for version in csxs_versions:
                os.system(f'reg add \"HKCU\\Software\\Adobe\\{version}\" /v PlayerDebugMode /t REG_DWORD /d 1 /f')
        print(f'✅ PlayerDebugMode включен для {len(csxs_versions)} версий CSXS: {csxs_versions}')
        return True
    except Exception as e:
        print(f'❌ Ошибка установки PlayerDebugMode: {e}')
        return False

def install():
    install_path = path_var.get()
    if not os.path.exists(install_path):
        os.makedirs(install_path, exist_ok=True)
    success = extract_files(install_path)
    if debug_var.get():
        set_player_debug_mode()
    if success:
        messagebox.showinfo('✅ Успешно', f'Файлы установлены в: {install_path}')
        root.quit()

def browse_path():
    folder = filedialog.askdirectory()
    if folder:
        path_var.set(folder)

def animate_background(frame_index):
    frame = gif_frames[frame_index]
    bg_label.configure(image=frame)
    root.after(30, lambda: animate_background((frame_index + 1) % len(gif_frames)))
icon_data = b'AAABAAEAIBcAAAEAIAAEDAAAFgAAACgAAAAgAAAALgAAAAEAIAAAAAAAgAsAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAIAAACGAAAA8QAAAIEAAAByAAAAyAAAAMkAAADKAAAAywAAAMwAAADQAAAA1AAAAEIAAAAAAAAACAAAAGAAAADGAAAA9AAAAP0AAADrAAAArAAAAD0AAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAQAAAAAAAAAAAAAACQAAAMAAAAD/AAAAhQAAAJIAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAcAAAAAkAAACJAAAA8wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA4QAAAFYAAAABAAAAAAAAAAAAAAAAAAAAEQAAAIMAAACYAAAAJgAAAAAAAAAwAAAA5gAAAP8AAACDAAAAhgAAAP8AAAD/AAAA8gAAAMUAAAC9AAAAwgAAAM8AAABuAAAAbAAAAPoAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA4gAAADwAAAAAAAAAAAAAABUAAACjAAAA/gAAAP8AAADXAAAAkwAAAMQAAAD/AAAA/wAAAIIAAAB6AAAA/wAAAP8AAACpAAAACgAAAAUAAAAHAAAAEAAAACUAAADVAAAA/wAAAP8AAAD9AAAAswAAAHIAAADYAAAA/wAAAP8AAAD/AAAArQAAAAAAAAADAAAAjwAAAP4AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAggAAAHAAAAD/AAAA/wAAANAAAAB/AAAAgAAAAIUAAAByAAAATQAAAPcAAAD/AAAA/wAAAKwAAAAUAAAAAAAAADcAAADcAAAA/wAAAP8AAADsAAAAAAAAAAQAAACaAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAACEAAAAagAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAANQAAABtAAAA/AAAAP8AAADvAAAAOAAAAAAAAAAAAAAAAAAAAHsAAAD/AAAA/wAAAP4AAAAAAAAAAAAAACMAAADUAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD1AAAA0AAAAGAAAABtAAAA/wAAAP8AAAD2AAAA3AAAAN0AAADhAAAAyQAAAGoAAAD4AAAA/wAAAOgAAAAqAAAAAAAAAA4AAAAAAAAAaQAAAP4AAAD/AAAA8wAAAAAAAAAAAAAAAAAAAI8AAAD/AAAA/wAAAP8AAAD/AAAAxAAAAEwAAAAUAAAABAAAAHYAAAD/AAAA/wAAAK4AAAAYAAAAGAAAABwAAAAhAAAALAAAAOIAAAD/AAAA/QAAALQAAACLAAAAtQAAAIMAAADXAAAA/wAAAP8AAADBAAAAAwAAAA8AAAAyAAAAwAAAAP8AAAD/AAAA/wAAAMUAAAAiAAAAAAAAAAAAAAAAAAAAfgAAAP8AAAD/AAAAzgAAAHMAAAB2AAAAgAAAAIwAAAAyAAAAjAAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA8QAAAFUAAACTAAAAyQAAAOkAAAD/AAAA/wAAAP8AAAD1AAAATQAAAAAAAAAAAAAAAAAAAAAAAACJAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAEcAAAAYAAAAtgAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAPYAAAB8AAAABgAAAPoAAAD/AAAA/wAAAP8AAAD/AAAA/wAAANIAAAAUAAAAAAAAAAAAAAAAAAAAAAAAAH4AAADcAAAA2QAAANMAAADSAAAA1QAAANgAAADLAAAAKwAAAAAAAAAWAAAAhQAAANgAAAD0AAAA+QAAAPAAAADEAAAAXAAAAAMAAAAAAAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAAvgAAAAkAAAAAAAAAAAAAAAAAAAAAAAAAEAAAABoAAAAcAAAARQAAAHkAAACSAAAAigAAAFoAAAAOAAAABwAAAD8AAABOAAAAaQAAAFgAAABKAAAAPgAAAFAAAABLAAAASwAAACAAAAD3AAAA/wAAAP8AAAD/AAAA/wAAAP8AAADQAAAAEwAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEAAAAIgAAADmAAAA/QAAAP8AAAD/AAAA8QAAAKkAAABIAAAA3gAAAPoAAAD0AAAASgAAAAAAAAA7AAAA6gAAAPoAAADpAAAAQQAAAI4AAADGAAAA6QAAAP8AAAD/AAAA/wAAAPQAAABJAAAAAAAAAAAAAAAAAAAAAAAAAAkAAACWAAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAK0AAADhAAAA/wAAAPYAAABBAAAAAQAAAJUAAAD/AAAA/wAAAKYAAAAIAAAAAgAAAA0AAAAzAAAAwwAAAP8AAAD/AAAA/wAAAMAAAAAdAAAAAAAAAAAAAAAAAAAATgAAAPYAAAD/AAAA+wAAAK8AAABoAAAAdwAAAMoAAADhAAAAVAAAANkAAAD/AAAA8AAAADAAAAAkAAAA4QAAAP8AAADvAAAAQQAAAAAAAAAAAAAAAAAAAAAAAACEAAAA/wAAAP8AAAD/AAAA/wAAAL0AAABFAAAADwAAAAQAAACbAAAA/wAAAP8AAACxAAAAEAAAAAAAAAAAAAAAHQAAAD0AAAAWAAAA1AAAAP8AAAD4AAAApgAAALsAAAD+AAAA/wAAAK8AAAAGAAAAAAAAAAAAAAAAAAAAHgAAAMoAAAD/AAAA/wAAAP8AAAD/AAAA/wAAAPIAAADJAAAAZwAAALwAAAD/AAAA/QAAAF8AAAAAAAAAAAAAAAAAAAAAAAAAAAAAABEAAADPAAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA2gAAAEQAAAAAAAAAAAAAAAQAAACYAAAA/gAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAP8AAACSAAAAvgAAAP8AAAD9AAAAVQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAEQAAAM4AAAD/AAAA8wAAAIMAAABnAAAAowAAAPkAAAD/AAAAzQAAABwAAAAAAAAAAwAAAI0AAAD+AAAA/wAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA/wAAAIgAAACiAAAA/wAAAP8AAACTAAAAAgAAAAAAAAAAAAAACgAAACIAAAASAAAAzwAAAP8AAADoAAAAJAAAAAAAAAAZAAAA2wAAAP8AAADzAAAARgAAAAAAAAAAAAAAFAAAAKQAAAD+AAAA/wAAANcAAACWAAAAxAAAAP4AAAD/AAAAggAAAFsAAAD7AAAA/wAAAO8AAAB6AAAAMgAAAEEAAACgAAAAywAAADcAAADQAAAA/wAAAOsAAAAwAAAACAAAAEQAAADqAAAA/wAAAPUAAABKAAAAAAAAAAAAAAAAAAAAEwAAAIoAAACfAAAAJwAAAAAAAAAsAAAA4wAAAP8AAACFAAAADwAAALIAAAD/AAAA/wAAAP4AAADvAAAA9AAAAP8AAAD/AAAAnAAAANYAAAD/AAAA+wAAAMYAAAC8AAAA5gAAAP8AAAD/AAAA1AAAACEAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAAMAAAAAAAAAAAAAAAgAAAC9AAAA/wAAAIYAAAAAAAAAJAAAALIAAAD5AAAA/wAAAP8AAAD/AAAA/gAAANkAAABwAAAA3QAAAP8AAAD/AAAA/wAAAP8AAAD/AAAA+wAAANUAAABPAAAAAQAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAAgAAAIYAAAD2AAAAhQAAAAAAAAAAAAAAFAAAAGoAAACxAAAAxwAAALkAAACEAAAALQAAAA4AAABvAAAAiAAAAI4AAACTAAAAlgAAAJAAAABqAAAAJQAAAAAAAAAA/wAEA/sAAADhAAAAwAAAAIAAACCAAABwwAAAUOAAAAAAcAAAAPAAAADwBAEA8AAAAPgAIADwAAAAcAAB4ABgAcAA+AGAAPgAgABgIMAAAADhAAAA8wgAAP8MAAM='
icon_path = 'temp_icon.ico'
with open(icon_path, 'wb') as icon_file:
    icon_file.write(base64.b64decode(icon_data))
root = tb.Window(themename='superhero')
root.iconbitmap(icon_path)
root.title('Установщик AutoSlot')
root.geometry('600x400')
root.resizable(False, False)
gif_path = get_resource_path('background.gif')
image = Image.open(gif_path)
gif_frames = [ImageTk.PhotoImage(frame.convert('RGBA')) for frame in ImageSequence.Iterator(image)]
bg_label = tk.Label(root)
bg_label.place(x=0, y=0, relwidth=1, relheight=1)
animate_background(0)
frame = ttk.Frame(root, padding=10)
frame.place(relx=0.5, rely=0.5, anchor='center')
ttk.Label(frame, text='Выбери путь куда распакуем AutoSlot', font=('Arial', 12)).pack(pady=5)
path_var = tk.StringVar(value=get_default_install_path())
path_frame = ttk.Frame(frame)
path_frame.pack(fill='x')
path_entry = ttk.Entry(path_frame, textvariable=path_var, width=40)
path_entry.pack(side='left', padx=5, expand=True, fill='x')
browse_btn = ttk.Button(path_frame, text='📁 Обзор', command=browse_path)
browse_btn.pack(side='right')
debug_var = tk.BooleanVar(value=True)
debug_checkbox = ttk.Checkbutton(frame, text='Required (PlayerDebugMode = 1)', variable=debug_var)
debug_checkbox.pack(pady=10)
install_btn = ttk.Button(frame, text='🚀 Установить', command=lambda: threading.Thread(target=install).start())
install_btn.pack(pady=20)

def play_music():
    pygame.mixer.init()
    pygame.mixer.music.load(get_resource_path('audio.mp3'))
    pygame.mixer.music.play((-1))
threading.Thread(target=play_music, daemon=True).start()
root.mainloop()
